import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto_Mono, Source_Code_Pro , Roboto_Slab, Michroma } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const robotoMono= Roboto_Mono({
  variable:"--font-roboto-mono",
  subsets:["latin"]
});

const sourceCodePro= Source_Code_Pro({
  variable:"--font-source-code-pro",
  subsets:["latin"]
});

const robotoSlab= Roboto_Slab({
  variable:"--font-roboto-slab",
  subsets:["latin"]
});
const michroma= Michroma({
  weight: "400",  
  variable:"--font-michroma",
  subsets:["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoMono.className} ${robotoSlab.variable} ${michroma.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
